name: p310env
channels:
  - defaults
  - pyviz
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - arrow-cpp=21.0.0
  - asttokens=3.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bleach=6.3.0
  - bokeh=3.8.2
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorcet=3.1.0
  - comm=0.2.3
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - gflags=2.2.2
  - glog=0.5.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - holoviews=1.22.1
  - html5lib=1.1
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - ipykernel=6.31.0
  - ipython=8.30.0
  - ipywidgets=8.1.7
  - jansson=2.14
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_bokeh=4.0.5
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.9
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250814.1
  - libavif=1.3.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcups=2.4.15
  - libcurl=8.17.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.33.0
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libunistring=1.3
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown=3.8
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - narwhals=2.7.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.14.1
  - numpy-base=2.2.5
  - openldap=2.6.10
  - openssl=3.0.18
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - panel=1.8.5
  - param=2.3.1
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - re2=2025.11.05
  - readline=8.3
  - requests=2.32.5
  - s2n=1.5.14
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - snappy=1.2.1
  - spirv-tools=2025.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - uc-micro-py=1.0.3
  - utf8proc=2.6.1
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xarray=2025.4.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xyzservices=2025.4.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - certifi==2025.11.12
      - cramjam==2.11.0
      - curl-cffi==0.13.0
      - et-xmlfile==2.0.0
      - fastparquet==2025.12.0
      - frozendict==2.4.7
      - fsspec==2025.12.0
      - h11==0.16.0
      - lxml==6.0.2
      - matplotlib==3.10.8
      - multitasking==0.0.12
      - numpy==2.2.6
      - openpyxl==3.1.5
      - outcome==1.3.0.post0
      - pandas-datareader==0.10.0
      - peewee==3.18.3
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - selenium==4.39.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8.1
      - trio==0.32.0
      - trio-websocket==0.12.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - websocket-client==1.9.0
      - websockets==15.0.1
      - wsproto==1.3.2
      - yfinance==1.0
prefix: /uufs/chpc.utah.edu/common/home/u1154915/.conda/envs/p310env
